OLED_ENABLE = yes
OLED_DRIVER = SSD1306
CONSOLE_ENABLE = no
MOUSEKEY_ENABLE = no
COMMAND_ENABLE = no

SPLIT_KEYBOARD = yes

ENCODER_ENABLE = no
EXTRAKEY_ENABLE = yes

RGBLIGHT_ENABLE = yes

WPM_ENABLE = yes
LTO_ENABLE = yes
EXTRAFLAGS += -flto
